version: "3.9"

services:
  app:
    build: .
    container_name: aanaya-app

    ports:
      - "8000:8000"

    volumes:
      - .:/var/www
      - /var/www/vendor
      - /var/www/node_modules

    env_file:
      - .env

    stdin_open: true
    tty: true
